blog/urls.py
from django.urls import path
from .views import Home, CreateNewPost, PostDetailView, UpdatePostView, DeletePostView

app_name = "blog"
urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("posts/new", CreateNewPost.as_view(), name="post-new"),
    path("post/<int:pk>/update", UpdatePostView.as_view(), name="post-update"),
    path("post/<int:pk>/delete", DeletePostView.as_view(), name="post-delete"),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import (
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView, 
    PasswordResetCompleteView 
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path("user/", include("user.urls", namespace="user")),
    path("password-reset/", PasswordResetView.as_view(template_name="user/password_reset.html"), name="password_reset"),
    path("password-reset/done/", PasswordResetDoneView.as_view(template_name="user/password_reset_done.html"), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html"), name="password_reset_confirm"),
    path("password-reset-complete/", PasswordResetCompleteView.as_view(template_name="user/password_reset_complete.html"), name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, reverse_lazy
from .views import RegisterView, me
from .forms import CustomAuthenticationForm
from django.contrib.auth.views import (
    LogoutView, 
    LoginView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView, 
    PasswordResetCompleteView 
)

app_name = "user"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("login/", LoginView.as_view(template_name="user/login.html", authentication_form=CustomAuthenticationForm), name="login"),
    path("me/", me, name="profile"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})

blog/forms.py
from .models import Post
from django import forms

class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "user-form-input",
        "placeholder" : "Title",
        "maxLength": 50
    }))
    
    content = forms.CharField(widget=forms.Textarea(attrs={
        "class": "user-form-input",
        "placeholder": "Content",
        "rows": 5
    }))
    class Meta:
        model = Post
        fields = ["title", "content"]

blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post
from django.views import View
from .forms import PostForm
# Create your views here.

class Home(ListView):
    model = Post
    template_name = "blog/home.html"
    ordering= ["-created_at"]
    context_object_name = "posts"
    paginate_by = 2

class CreateNewPost(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class PostDetailView(DetailView):
    model=Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'

class UpdatePostView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
   

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    
    
class DeletePostView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}My Website{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/styles.css' %}" />
  </head>
  <body>
    <div class="header">
      <nav>
        <ul>
          <li><a href="{% url 'blog:home' %}">Home</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'user:profile' %}">Profile</a></li>
          <li><a href="{% url 'blog:post-new' %}">New Post</a></li>
          <li>
            <form
              action="{% url 'user:logout' %}"
              method="POST"
              style="display: inline"
            >
              {% csrf_token %}
              <button type="submit" class="logout-button">Logout</button>
            </form>
          </li>

          <p>Welcome {{ user.username }}</p>
          {% else %}
          <li><a href="{% url 'user:register' %}">Register</a></li>
          <li><a href="{% url 'user:login' %}">Login</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
    <div class="content">{% block content %} {% endblock %}</div>
  </body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Recent Posts</h1>
    <hr/>
    {% for post in posts %}
    <div class="card mb-4">
        <div class="card-body">
            <div style="display: flex; align-items: center; justify-content: start;">
                <img src="{{ post.author.profile.profile_image.url }}" alt="{{ post.author.username }}'s profile picture" class="profile-image">
                <h2>
                    <a href="{% url 'blog:post-detail' post.id %}" class="card-title">{{ post.title }}</a>
                </h2>
            </div>
            <p>
                By <strong>{{ post.author.username }}</strong> on {{ post.created_at|date:"F j, Y, g:i a" }}
            </p>
            <p>{{ post.content|truncatewords:30 }}</p>
        </div>
        <hr/>
    </div>
    {% endfor %}
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo; Previous</span>
                </a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">Next &raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <p style="text-align: center">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</p>
    {% endif %}

</div>
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block title %}Delete Post{% endblock title %}
{% block content %}
<div class="container mt-4">
    <h2>Delete Post</h2>
    <p>Are you sure you want to delete the post titled "{{ post.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm Delete</button>
        <a href="{% url 'blog:post-detail' post.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %} 

{% block title %}
{{ post.title }}
{% endblock title %} 

{% block content %}
<div class="container mt-4">
  <div class="post-detail">
    <h1 class="post-title">{{ post.title }}</h1>
    <p class="post-meta">
            By <strong>{{ post.author.username }}</strong> on {{ post.created_at|date:"F j, Y, g:i a" }}
        </p>
    
    <div class="post-content">{{ post.content|linebreaks }}</div>
        {% if user.username == post.author.username %}
        <a href="{% url "blog:post-update" post.id %}" class="btn btn-secondary"> Update </a>
        <a href="{% url "blog:post-delete" post.id %}" class="btn btn-secondary">  Delete </a>
        {% endif %}
</div>
</div>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% if form.non_field_errors %}
        <div class="user-form-error">
            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <div class="user-form-group">
        {{ form.title.label_tag }}
        {{ form.title }}
        {% if form.title.errors %}
            <div class="user-form-error">
                {{ form.title.errors }}
            </div>
        {% endif %}
    </div>
    <div class="user-form-group">
        {{ form.content.label_tag }}
        {{ form.content }}
        {% if form.content.errors %}
            <div class="user-form-error">
                {{ form.content.errors }}
            </div>
        {% endif %}
    </div>
    <button type="submit" class="user-form-btn btn-primary">Save Post</button>
</form>

{% endblock content%}